### ISSUE TITLE
Get-ADOPSUser

### ISSUE THREAD

**Issue by bjompen** [AZDOPS/AZDOPS#113]
We need a feature to search for users using
- Username
- Displayname
- GUID / User ID

**Comment by krokofant** [comment]
Which GUID or User ID is it that should be used? If it's suppose to be used in further ADO Commands the User Descriptor seems to be more used than the User ID.

Searching for User Descriptor is for example the default way of fetching users.

**Comment by bjompen** [comment]
I... Honestly don't remember (blame vacation brain 😂)
Descriptor is great for starters and we can see what more we need in the future.

One thing we might want to add, either here or in another function, is returning data from the [legacy descriptors as well.](https://docs.microsoft.com/en-us/rest/api/azure/devops/ims/identities/read-identities?view=azure-devops-rest-7.1)
This API is needed to set permissions in Azure DevOps.
(*humblebrag* see [my blogpost about it](https://bjompen.com/#/posts/holdmydecompiler) */humblebrag*)

I think its better to have this separately.. but what do you think?
