### ISSUE TITLE
Even non-public functions are exported

### ISSUE THREAD

**Issue by krokofant** [AZDOPS/AZDOPS#117]
Currently all functions are exported from `Classes/*`, `Private/*`, `Public/*`.

It seems reasonable to lock this down so that the only functions that are exported are those meant for public usage.

**Comment by bjompen** [comment]
This is actually on purpose. The development non built module exports everything as it makes it easier to test and explore APIs.

For example, the possibility to use InvokeADOPSRestMethod directly without entering a debug session allows building functions outside of the module before putting them in the module.

We do fix this with the build script.
Run `Invoke-Build` in the root folder of the repo and it will output a compiled module in your ./bin folder where you have the module in order for release.

This said: I'm going to deny the PR for now, But will gladly accept reasoning to change this :)

**Comment by krokofant** [comment]
@bjompen Interesting solution there with the build file! Thanks for taking a look 😄
