### ISSUE TITLE
New-ADOPSEnvironment

### ISSUE THREAD

**Issue by krokofant** [AZDOPS/AZDOPS#125]
**Is your feature request related to a problem? Please describe.**
Environment should be able to be added, and with this we should also work around [this weird issue](https://developercommunity.visualstudio.com/t/Pipeline-environment-security-enhancemen/1236351?space=21&q=environment+permission&sort=votes&page=4) that prohibits one from having default permissions on newly created environments.

A newly created environment will only add the creator as an administrator. For simplicity the project administrators or a custom group like _Environment Administrators_ could be linked to the administrator role for the environment.

**Describe the solution you'd like**
`New-ADOPSEnvironment -Name {name} -Group 'Custom Administrators' -Description {description}  -Organiozation {org} -Project {project}`

Where the Group by default can be the project administrators. Maybe an alternative switch to maintain the weird standard behavior `-SkipAdmin`.

**Additional context**
https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/environments/add?view=azure-devops-rest-6.0

**Comment by bjompen** [comment]
Great idea! Ill tag it in for release 1.2.0, next code release.
