### ISSUE TITLE
Standardise test design - Headlines

### ISSUE THREAD

**Issue by bjompen** [AZDOPS/AZDOPS#128]
All unit tests should follow the same naming standard and layout for `Describe` and `Context` blocks where this is possible

My suggestion is something like this

```PowerShell
Describe 'CommandName' {
  BeforeAll {
    # Standard mocks
  }
  Context 'General function tests' {
    # Test parameters and similar data. Not code paths
  }
  Context 'Functionality' {
    # Test code paths and results.
  }
}

Describe 'Bug fixes' {
  It 'Verifies bug number [link to issue]' {
    # Replicates reported issue behaviour
  }
}
```

If needed, add more context blocks, but try to keep these so its easy to follow tests missing, tests for reported bugs, what would require a major, minor, or build number bump, and so on.

**Comment by krokofant** [comment]
I started this but changed to use a common way of checking the parameters in the top `Describe`. The context "General function tests" or "Parameters" doesn't add anything when the test itself specifies "Has parameter [...]".

I think it's easier to see if the standard "Has parameter [...]" tests are missing if that is the top most thing that's tested.

The "Functionality" context is a bit confusing to me, I don't get what specifically should be included there instead of in another dedicated Context block. A context could be something like `-Unique parameter set` and then inside of that you'd have different types of test cases with different input and output.

**Comment by bjompen** [comment]
> I started this but changed to use a common way of checking the parameters in the top `Describe`. The context "General function tests" or "Parameters" doesn't add any more context when the test itself specifies "Has parameter [...]".

Related to #127 
This is one of the things I had in mind for this refactor, so changing to a standard way here is great.
The reason to separate this and testing code paths in to separate headlines is to easier see whether we need to bump versions or not.
If a parameter that is, or becomes, mandatory changes behaviour that is a breaking change and we need to do a major bump.
If a non mandatory parameter for example changes default value that _could_ be a major bump.
If a non mandatory parameter is added that's a minor bump, and so on..

> I think it's easier to see if the standard "Has parameter [...]" tests are missing if that is the top most thing that's tested.

Same as above, one of the things I had in mind is gather these tests up top.

> The "Functionality" context is a bit confusing to me, I don't get what specifically should be included there instead of in another dedicated Context block. A context could be something like `-Unique parameter set` and then inside of that you'd have different types of test cases with different input and output.

Regarding the name of the context I'm absolutely not 100% certain what it should be. The main point is to separate the code path tests as these can be refactored any way we want as long as everything keeps working.

So Absolutely, we can have multiple "not input standard related" context blocks.

Maybe tags and different names are a better way to go:

```
Context 'Testing parameter set bla bla' -Tag 'Functionality' {
  It 'Given -xyz it shouold ABC' {
```

**Comment by bjompen** [comment]
After looking at your PR I think I understand what you mean by 
> think it's easier to see if the standard "Has parameter [...]" tests are missing if that is the top most thing that's tested.

I do want them wrapped in a context block at least. something like this:

```PowerShell
Context 'Parameter validation' {
        It 'Has parameter <_.Name>' -TestCases @(
            @{ Name = 'Username'; Mandatory = $true }
            @{ Name = 'PersonalAccessToken'; Mandatory = $true }
            @{ Name = 'Organization'; Mandatory = $true }
            @{ Name = 'Default'; Type = [switch] }
        ) {
            Get-Command -Name Connect-ADOPS | Should -HaveParameter $Name -Mandatory:([bool]$Mandatory) -Type $Type
        }
    }
```

The reason is the colourful and easy to see output in the console.
![image](https://user-images.githubusercontent.com/17783007/181463062-8061e471-9ca7-4ffa-bb36-5a6942a0f497.png)
versus
![image](https://user-images.githubusercontent.com/17783007/181463130-0496922b-69ea-49fe-b53f-ea1670295655.png)

I at least think its easier to get a quick view of where in the test suite we are like this..

**Comment by krokofant** [comment]
> If a parameter that is, or becomes, mandatory changes behaviour that is a breaking change and we need to do a major bump.

If a mandatory parameter becomes not mandatory, then that would not be a breaking change. But it would still be nice to catch these changes.

The unified way of testing the parameters have one notable flaw, which is related to [this pester issue](https://github.com/pester/Pester/issues/2105). We cannot easily assert that an existing parameter is non-mandatory, we can only assert that a given parameter is mandatory. This is a limitation of the current -HaveParameter operator.

I've added a stricter version of the -HaveParameter to the code for now until this is improved in Pester.

**Comment by bjompen** [comment]
I really appreciate the hard work you're doing here! fantastic!
I know it's "just" a draft still, but a friendly request would be to separate the PR when done, and add related tasks to each solution.
I started reviewing it as is, but quickly lost track of what relates to what, and why.

Again, I really really appreciate it, so not at all meant as a complaint, just a friendly request :)

**Comment by krokofant** [comment]
Yeah, sorry about that. I might've got a little carried away over the night there. 😅 I usually clean up the commits or do a squash before merging.

I'm away for a week so if you want to give some of these things a go you can go ahead and I'll pick up and rebase what I can.

The pester issue made things a bit more ugly. I'll try to split these changes up, but so far the changes seems very intertwined. Moving around the parameter tests will update the headlines for instance.

**Comment by bjompen** [comment]
Most of the things here is now fixed in various PRs. As for headlines, Some of them are standardized, some not, and for now, thats close enough.
