### ISSUE TITLE
Get-ADOPSUser with -Name parameter does not return expected results

### ISSUE THREAD

**Issue by SimonWahlin** [AZDOPS/AZDOPS#183]
**Describe the bug**
This returns a user as expected:
`Get-ADOPSUser | ? displayName -eq 'myProject Build Service (MyOrg)'`

This returns nothing:
`Get-ADOPSUser -Name 'myProject Build Service (MyOrg)'`

**To Reproduce**
Run the above commands

**Expected behavior**
I expect the above commands to have the same output

**Comment by bjompen** [comment]
The issue here is that there is no way of querying the AZDO Graph API for a username, and the list of users from the _queryable_ API is limited to only AAD/EntraID users, not for example build accounts.

A workaround is in the connected PR.
