### ISSUE TITLE
Add-ADOPSScaleSet

### ISSUE THREAD

**Issue by bjompen** [AZDOPS/AZDOPS#2]
Add an Azure VM Scale set Agent pool

**Comment by SebastianClaesson** [comment]
This function will need some other functions to work;
- Manage/delete/add Elastic Pools
- Manage/delete/add nodes

**Comment by SebastianClaesson** [comment]
Also identified we need to create/manage service endpoints to get this in place.

**Comment by bjompen** [comment]
@SebastianClaesson is this closed with #96 ? New-ADOPSElasticPool should be whats needed to set up the scale sets

**Comment by bjompen** [comment]
Closed with #119 and #96
