### ISSUE TITLE
`Get-ADOPSProjectRetentionSettings` / `Set-ADOPSProjectRetentionSettings`

### ISSUE THREAD

**Issue by coolhome** [AZDOPS/AZDOPS#207]
**Is your feature request related to a problem? Please describe. **
New Feature - `Get-ADOPSProjectRetentionSettings` / `Set-ADOPSProjectRetentionSettings`

**Describe the solution you'd like**

**Additional context**

I will likely implement this when I get time. This should help keep project settings consistent :)

Reference:
* https://learn.microsoft.com/en-us/rest/api/azure/devops/build/retention/get?view=azure-devops-rest-7.1
* https://learn.microsoft.com/en-us/rest/api/azure/devops/build/retention/update?view=azure-devops-rest-7.1

**Comment by bjompen** [comment]
Awesome! Assigned it to you and added a new milestone for new features.
