### ISSUE TITLE
Function: Publish a Git repository to a wiki - `Publish-ADOPSGitWiki`

### ISSUE THREAD

**Issue by StefanIvemo** [AZDOPS/AZDOPS#77]
**Is your feature request related to a problem? Please describe.**

We should have a function to publish a git repository to a wiki, `Publish-AZDOPSGitWiki`.

**Describe the solution you'd like**

It should work similar to `az devops wiki create`. 

**Additional context**

**Comment by bjompen** [comment]
@StefanIvemo Any updates on this? Anything I can help with?

**Comment by StefanIvemo** [comment]
Haven't had the time to start with this yet.
