### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by bjompen** [AZDOPS/AZDOPS#80]
We probably should have checked name availability before choosing, but here we are.

AZDOPS is taken in powershell gallery and hence we need to rename the module.
Suggestions are
- ADOPS
  - Available in the gallery
  - Taken on github
- PSAZDO
  - Available on gallery
  - Available on github
- PSADO
  - Available on gallery
  - Taken on github
  
Votes for or against?

**Comment by StefanIvemo** [comment]
Keep AZDOPS as org name. And name the repo ADOPS.

**Comment by bjompen** [comment]
5 rockets for ADOPS - Will rename the module.
