### ISSUE TITLE
Add exclusion list to standard tests.

### ISSUE THREAD

**Issue by bjompen** [AZDOPS/AZDOPS#98]
A short lived standard.. 
The default test "All public functions should have organization parameter" is not needed on the `[New-ADOPSElasticPoolObject](https://github.com/AZDOPS/AZDOPS/blob/main/Source/Public/New-ADOPSElasticPoolObject.ps1)` command. We need to have a way of excluding it from this test to have the test working again.

Either we create an exclusion list in the tests file itself (`$ExcludeStandardPArams = @()`) or we try to make it really dynamic and implement a helper attribute we can use, something like this:
```
SkipTest attribute

Here is a new attribute for this example.

Class SkipTest : Attribute {
    [string]$TestName

    MyCommand([string]$Name)
    {
        $this.TestName = $Name
    }
}

Sample function

The we attach it to an advanced function.

function Do-Something
{
    [SkipTest('HelpDescription')]
    [cmdletbinding()]
    param()
    return $true
}
```

blatantly stolen from [Kevin Marquette](https://powershellexplained.com/2017-02-19-Powershell-custom-attribute-validator-transform/)

What do you think?

**Comment by PalmEmanuel** [comment]
I like the attribute solution, feels more structured.
